name: shopping_list
description: A shopping list app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  image_picker: ^0.8.4+4
  path_provider: ^2.0.14
  file_picker: ^4.0.10
  settings_ui: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets\icon\icon.png

flutter:
  uses-material-design: true
